version: '3'
services:
    website:
        build: ./website
        container_name: website
        volumes: 
            - ./website:/home/app/src
        depends_on:
            - database
        ports:
            - '127.0.0.1:5000:5000'

        env_file: "secrets.env"
        
        user: app
        stdin_open: true
        tty: true

        command: python3 -m flask run --host 0.0.0.0 --debug



    database:
        image: postgres:alpine
        container_name: database
        volumes:
            - ./database:/var/lib/postgresql/data

        env_file: "secrets.env"
