services:
    database:
        image: postgres:alpine
        container_name: database
        volumes:
            - ../../../db_mount:/var/lib/postgresql/data
        networks:
            - dictionary
        ports:
            - '127.0.0.1:5432:5432'

        env_file: ./secrets.env


networks:
    dictionary:
        external: true
